#!/bin/bash

set -e

cd "$(dirname "$0")/../builtinFonts"

echo "// The contents of this file are generated by ./lib/EpdFont/scripts/build-font-ids.sh"
echo "#pragma once"
echo ""

echo "#define YOUNGSERIF_12_FONT_ID ($(
ruby -rdigest -e 'puts [
  "./youngserif_12_regular.h",
  "./youngserif_12_bold.h",
  "./youngserif_12_bolditalic.h",
  "./youngserif_12_italic.h",
].map{|f| Digest::SHA256.hexdigest(File.read(f)).to_i(16) }.sum % (2 ** 32) - (2 ** 31)'
))"

echo "#define YOUNGSERIF_14_FONT_ID ($(
ruby -rdigest -e 'puts [
  "./youngserif_14_regular.h",
  "./youngserif_14_bold.h",
  "./youngserif_14_bolditalic.h",
  "./youngserif_14_italic.h",
].map{|f| Digest::SHA256.hexdigest(File.read(f)).to_i(16) }.sum % (2 ** 32) - (2 ** 31)'
))"

echo "#define YOUNGSERIF_16_FONT_ID ($(
ruby -rdigest -e 'puts [
  "./youngserif_16_regular.h",
  "./youngserif_16_bold.h",
  "./youngserif_16_bolditalic.h",
  "./youngserif_16_italic.h",
].map{|f| Digest::SHA256.hexdigest(File.read(f)).to_i(16) }.sum % (2 ** 32) - (2 ** 31)'
))"

echo "#define YOUNGSERIF_18_FONT_ID ($(
ruby -rdigest -e 'puts [
  "./youngserif_18_regular.h",
  "./youngserif_18_bold.h",
  "./youngserif_18_bolditalic.h",
  "./youngserif_18_italic.h",
].map{|f| Digest::SHA256.hexdigest(File.read(f)).to_i(16) }.sum % (2 ** 32) - (2 ** 31)'
))"

echo "#define DMSANS_12_FONT_ID ($(
ruby -rdigest -e 'puts [
  "./dmsans_12_regular.h",
  "./dmsans_12_bold.h",
  "./dmsans_12_bolditalic.h",
  "./dmsans_12_italic.h",
].map{|f| Digest::SHA256.hexdigest(File.read(f)).to_i(16) }.sum % (2 ** 32) - (2 ** 31)'
))"

echo "#define DMSANS_14_FONT_ID ($(
ruby -rdigest -e 'puts [
  "./dmsans_14_regular.h",
  "./dmsans_14_bold.h",
  "./dmsans_14_bolditalic.h",
  "./dmsans_14_italic.h",
].map{|f| Digest::SHA256.hexdigest(File.read(f)).to_i(16) }.sum % (2 ** 32) - (2 ** 31)'
))"

echo "#define DMSANS_16_FONT_ID ($(
ruby -rdigest -e 'puts [
  "./dmsans_16_regular.h",
  "./dmsans_16_bold.h",
  "./dmsans_16_bolditalic.h",
  "./dmsans_16_italic.h",
].map{|f| Digest::SHA256.hexdigest(File.read(f)).to_i(16) }.sum % (2 ** 32) - (2 ** 31)'
))"

echo "#define DMSANS_18_FONT_ID ($(
ruby -rdigest -e 'puts [
  "./dmsans_18_regular.h",
  "./dmsans_18_bold.h",
  "./dmsans_18_bolditalic.h",
  "./dmsans_18_italic.h",
].map{|f| Digest::SHA256.hexdigest(File.read(f)).to_i(16) }.sum % (2 ** 32) - (2 ** 31)'
))"

echo "#define SMALL_FONT_ID ($(
ruby -rdigest -e 'puts [
  "./steinem_8_regular.h",
  "./steinem_8_bold.h",
  "./steinem_8_bolditalic.h",
  "./steinem_8_italic.h",
].map{|f| Digest::SHA256.hexdigest(File.read(f)).to_i(16) }.sum % (2 ** 32) - (2 ** 31)'
))"

echo "#define UI_10_FONT_ID ($(
ruby -rdigest -e 'puts [
  "./steinem_10_regular.h",
  "./steinem_10_bold.h",
  "./steinem_10_bolditalic.h",
  "./steinem_10_italic.h",
].map{|f| Digest::SHA256.hexdigest(File.read(f)).to_i(16) }.sum % (2 ** 32) - (2 ** 31)'
))"

echo "#define UI_11_FONT_ID ($(
ruby -rdigest -e 'puts [
  "./steinem_11_regular.h",
  "./steinem_11_bold.h",
  "./steinem_11_bolditalic.h",
  "./steinem_11_italic.h",
].map{|f| Digest::SHA256.hexdigest(File.read(f)).to_i(16) }.sum % (2 ** 32) - (2 ** 31)'
))"

echo "#define UI_12_FONT_ID ($(
ruby -rdigest -e 'puts [
  "./steinem_12_regular.h",
  "./steinem_12_bold.h",
  "./steinem_12_bolditalic.h",
  "./steinem_12_italic.h",
].map{|f| Digest::SHA256.hexdigest(File.read(f)).to_i(16) }.sum % (2 ** 32) - (2 ** 31)'
))"

echo "#define UI_14_FONT_ID ($(
ruby -rdigest -e 'puts [
  "./steinem_14_regular.h",
  "./steinem_14_bold.h",
  "./steinem_14_bolditalic.h",
  "./steinem_14_italic.h",
].map{|f| Digest::SHA256.hexdigest(File.read(f)).to_i(16) }.sum % (2 ** 32) - (2 ** 31)'
))"

echo "#define UI_18_FONT_ID ($(
ruby -rdigest -e 'puts [
  "./steinem_18_regular.h",
  "./steinem_18_bold.h",
  "./steinem_18_bolditalic.h",
  "./steinem_18_italic.h",
].map{|f| Digest::SHA256.hexdigest(File.read(f)).to_i(16) }.sum % (2 ** 32) - (2 ** 31)'
))"

echo "#define UI_21_FONT_ID ($(
ruby -rdigest -e 'puts [
  "./steinem_21_regular.h",
  "./steinem_21_bold.h",
  "./steinem_21_bolditalic.h",
  "./steinem_21_italic.h",
].map{|f| Digest::SHA256.hexdigest(File.read(f)).to_i(16) }.sum % (2 ** 32) - (2 ** 31)'
))"

echo "#define UI_32_FONT_ID ($(
ruby -rdigest -e 'puts [
  "./steinem_32_regular.h",
  "./steinem_32_bold.h",
  "./steinem_32_bolditalic.h",
  "./steinem_32_italic.h",
].map{|f| Digest::SHA256.hexdigest(File.read(f)).to_i(16) }.sum % (2 ** 32) - (2 ** 31)'
))"
